language: ruby
cache: bundler
rvm:
- 2.4.1
sudo: false
script:
- bundle exec rake db:setup
- bundle exec rake spec
notifications:
  slack:
    secure: Un/OaiSmAHjiYDdYpS8GLpkxclZLpKedIRvqwcl1hGWfQSvmUnseXZNRoIMjxpEaKyIN29UKZVN563AGB06tEDG9h1k3t2hB1k+LG+yOnKRzAkMgUWQELPvLxr6uQ3B6Ul7WtBQvy8GIWrW8iGJ7GEJ/ZTGP8YE6VMQ+p97F60NONjoWffgBT4kDqJ3iRxp77Dnu6W+dACPfhhc4hGTF7szNdScyFgocqnHq+vq6qPY1b8jQUzQrHHm0lykscRlHg5l5xmf1XaV381f8KTVZWBLnNa61WGOw/IpNFlj1cbpZAhZNIzSiCjQ7GhMnZCm+sSWMjJ7xYgSrn51r/fxKzTygxDcQHA3WYk0g58iQnr/zM9zEnqqImFKlnkW83tAjVze74Uw3J9dTKAc8oYQ2ZUNci9tC94gLvrAmh+eTFoGWdGF3dh1xE3Jge4lf6Ux2nNiKAO7wmGGEJ7L2PBoyPFaPsDDwztphQW2Jkh85spATOiN2iNgzpsfGhTWDPnfkMtugSvsYtXQ5RO35/mrYjXVm5xNTF71frFCEBoYZDP4w/6at4uzwZv0Mk96UEuKvWR6NU+W3HMO2WdmFeJVStSRHBbwszHw1SVDHBwWWL6ALQH6q9gOb0CGCsVLvJvoOoEB4a2IUe2V9RJq/EX6ACLLhc4kapPa5+dIMI5ow8Nc=
